/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
// TODO: Might use some optimization.
#include <iostream>

int main (int argc, char ** argv) {
    unsigned int current = 1, precedent = 1, temp = 0, sum = 0;

    while (current <= 4000000) {
        temp = current + precedent;
        precedent = current;
        current = temp;

        if ((current % 2) == 0) {
            std::cout << "Even: " << current << std::endl;
            sum += current;
        } else {
            std::cout << "Odd:  " << current << std::endl;
        }
    }

    std::cout << "Total: " << sum << std::endl;

    return 0;
}